name: develop->mainへのPR作成
on:
  pull_request:
    branches:
      - develop
    types:
      - closed

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2

      - name: GitHub Pull Request Action for master
        # NOTE: https://github.com/repo-sync/pull-request
        uses: repo-sync/pull-request@v2.5
        with:
          source_branch: "develop"
          destination_branch: "main"
          pr_title: "$(date +%Y-%m-%d) Release"
          pr_draft: false
          pr_allow_empty: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
