name: develop<-topic のPR作成
on:
  pull_request:
    branches:
      - future
    types:
      - opened

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 出力パラメータの設定 'branch name'
        # https://thaim.hatenablog.jp/entry/2019/10/22/153354
        # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#set-an-output-parameter-set-output
        id: set_branch_name
        env:
          BRANCH_NAME: ${{github.head_ref}}
          BASE_BRANCH_NAME: ${{github.base_ref}}
        run: |
          echo ::set-output name=branch::${BRANCH_NAME}
          echo ${BRANCH_NAME}

      - name: 出力パラメータの確認
        run: |
          echo ${{ steps.set_branch_name.outputs.branch }}

      - name: PR作成 'develop <- topic'
        # NOTE: https://github.com/repo-sync/pull-request
        uses: repo-sync/pull-request@v2.5
        with:
          source_branch: ${{ steps.set_branch_name.outputs.branch }}
          destination_branch: "develop"
          pr_title: "develop <= ${{ steps.set_branch_name.outputs.branch }} at $(date +%Y-%m-%d)"
          pr_draft: false
          pr_allow_empty: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
